name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium

    - name: Verify secrets (for debugging purposes)
      env:
       USERNAME: ${{ secrets.USERNAME }}
       PASSWORD: ${{ secrets.PASSWORD }}
      run: |
       echo "USERNAME: $USERNAME"
       echo "PASSWORD: $PASSWORD"
      # REMOVE this step after verification to avoid exposing secrets in logs.

    - name: Run Playwright tests
      run: npx playwright test
      env:
        USERNAME: ${{ secrets.USEREMAIL }}
        PASSWORD: ${{ secrets.PASSWORD }}
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
